name: wanandroid_flutter
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  get: ^4.6.6
  pull_to_refresh: ^2.0.0
  flutter_screenutil: ^5.9.0
  logger: ^2.2.0
  cached_network_image: ^3.3.1
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  pretty_dio_logger: ^1.3.1
  encrypt: ^5.0.3
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  extended_nested_scroll_view: ^6.2.1
  permission_handler: ^11.3.1
  easy_localization: ^3.0.2
  flutter_svg: ^2.0.10+1
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  lottie: ^3.1.0
  easy_refresh: ^3.4.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  retrofit_generator: ^8.1.0

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/translations/


